inherit_from:
  - ../../../.rubocop.yml

Lint/UselessAssignment:
  Enabled: false
Layout/IndentationStyle:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
  